version: '3.8'
services:
 minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    env_file:
      - ".env"
    restart: always
    volumes:
      - "data:/data"
volumes:
  data:
    driver: local
